version: "2.2"
services:
  selenium:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
  chromedriver:
    image: chromedriver
    build: ./build/chromedriver
    init: true
    command:
      - chromedriver
      - --whitelisted-ips
    volumes:
      - /dev/shm:/dev/shm
  scraping:
    image: docker-scraping
    build: ./build/scraping
    volumes:
      - .:/var/lib/python3
    entrypoint:
      - docker-entrypoint.sh
    depends_on:
      - selenium
      - chromedriver
